mode: LeastConnection
label_selector:
  app.kubernetes.io/instance: default.test
  app.kubernetes.io/managed-by: opentelemetry-operator
config:
  scrape_configs:
  - job_name: prometheus

    file_sd_configs:
    - files:
      - file_sd_test_1.yaml

    static_configs:
    - targets: ["prom.domain:9001", "prom.domain:9002", "prom.domain:9003"]